version: '3.1'
services:
  db:
    image: postgres:latest
    ports:
      - 5434:${DB_PORT}
    environment:
       POSTGRES_DB: ${DB_NAME}
       POSTGRES_USER: ${DB_USERNAME}
       POSTGRES_PASSWORD: ${DB_PASSWORD}