spring:
  datasource:
    driverClassName: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none
  sql:
    init:
      platform: postgres
server:
  port: 8082
management:
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true