spring:
  datasource:
    url: jdbc:postgresql://db-product:5432/product-service
    username: postgres
    password: "{cipher}bd5fc08f73615af76090c70d9cecd2e8a35247dcadc6d0f1ad1b30c591a2e6ac"
  flyway:
    locations: classpath:/db/migration,classpath:/db/testdata
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eurekaserver:8761/eureka/
keycloak:
  realm: microservices-test-realm
  auth-server-url: http://keycloak:8080/auth
  ssl-required: external
  resource: microservices-test-client
  credentials:
    secret: 25c9192b-42a2-4fcd-8b34-087c7e0074a7
  use-resource-role-mappings: true
  bearer-only: true
server:
  forward-headers-strategy: native