spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres
server:
  port: 8081
management:
  endpoints:
    web:
      exposure:
        include: "*"