services:
  db:
    image: postgres:latest
    ports:
      - 5434:${DB_PORT}
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}